<?xml version="1.0" encoding="UTF-8"?><testrun name="M2PublicTests" project="harrypotter" tests="94" started="94" failures="33" errors="1" ignored="0">
  <testsuite name="harrypotter.tests.M2PublicTests" time="3.656">
    <testcase name="testOnGryffindorTraitTaskScenario1" classname="harrypotter.tests.M2PublicTests" time="0.764"/>
    <testcase name="testOnGryffindorTraitTaskScenario4" classname="harrypotter.tests.M2PublicTests" time="0.021">
      <failure>java.lang.AssertionError: In all Tasks, if GryffindorTrait is activated it should allow the champion to cast two spells in his/her turn and update the spell CoolDown accordingly  expected:&lt;4&gt; but was:&lt;3&gt;
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at harrypotter.tests.M2PublicTests.testOnGryffindorTraitTaskScenario4(M2PublicTests.java:3566)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
    <testcase name="testOnGryffindorTraitTaskScenario6" classname="harrypotter.tests.M2PublicTests" time="0.03">
      <failure>java.lang.AssertionError: In SecondTask, when GryffindorTrait is activated and the champion moves to his/her treasure cell, he/she should no longer be the current champ. Actual: harrypotter.model.character.GryffindorWizard@2a4c3737
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failEquals(Assert.java:185)
	at org.junit.Assert.assertNotEquals(Assert.java:161)
	at harrypotter.tests.M2PublicTests.testOnGryffindorTraitTaskScenario6(M2PublicTests.java:3703)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
    <testcase name="testOnGryffindorTraitTaskScenario7" classname="harrypotter.tests.M2PublicTests" time="0.01">
      <failure>java.lang.AssertionError: In all Tasks, when GryffindorTrait is activated and the champion moves from a cell, it should be converted to an EmptyCell  expected:&lt;class harrypotter.model.world.EmptyCell&gt; but was:&lt;class harrypotter.model.world.ChampionCell&gt;
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at harrypotter.tests.M2PublicTests.testOnGryffindorTraitTaskScenario7(M2PublicTests.java:3854)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
    <testcase name="testOnGryffindorTraitTaskScenario8" classname="harrypotter.tests.M2PublicTests" time="0.008">
      <failure>java.lang.AssertionError: In all Tasks, when GryffindorTrait is activated and the champion moves from a cell, it should be converted to an EmptyCell  expected:&lt;class harrypotter.model.world.EmptyCell&gt; but was:&lt;class harrypotter.model.world.ChampionCell&gt;
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at harrypotter.tests.M2PublicTests.testOnGryffindorTraitTaskScenario8(M2PublicTests.java:3968)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
    <testcase name="testOnGryffindorTraitTaskScenario9" classname="harrypotter.tests.M2PublicTests" time="0.004">
      <failure>java.lang.AssertionError: In SecondTask, when GryffindorTrait is activated the MerPeople should not attack until the champion makes his/her two actions.
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at harrypotter.tests.M2PublicTests.testOnGryffindorTraitTaskScenario9(M2PublicTests.java:4078)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
    <testcase name="testMethodHealingSpellCallsUseSpell" classname="harrypotter.tests.M2PublicTests" time="0.028"/>
    <testcase name="testMoveForwardToEggCellSecondTask" classname="harrypotter.tests.M2PublicTests" time="0.008">
      <failure>java.lang.AssertionError: When a champion moves forward from a cell, it should be converted to an EmptyCell  expected:&lt;class harrypotter.model.world.EmptyCell&gt; but was:&lt;class harrypotter.model.world.ChampionCell&gt;
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at harrypotter.tests.M2PublicTests.testMoveForwardToEggCellSecondTask(M2PublicTests.java:3084)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
    <testcase name="testOnSlytherinTraitFirstTaskSetsDirectionVariableInSlythWizard" classname="harrypotter.tests.M2PublicTests" time="0.004"/>
    <testcase name="testEncounterMerPeopleChampionDead" classname="harrypotter.tests.M2PublicTests" time="0.004">
      <failure>java.lang.AssertionError: Hp of the champion should have reached zero expected:&lt;0&gt; but was:&lt;40&gt;
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at harrypotter.tests.M2PublicTests.testEncounterMerPeopleChampionDead(M2PublicTests.java:1004)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
    <testcase name="testEncounterOneMerPerson" classname="harrypotter.tests.M2PublicTests" time="0.068"/>
    <testcase name="testFinalizeActionMethodInClassTask" classname="harrypotter.tests.M2PublicTests" time="0.002"/>
    <testcase name="testTaskListenerVariableSetter" classname="harrypotter.tests.M2PublicTests" time="0.001"/>
    <testcase name="testMethodUsePotions1" classname="harrypotter.tests.M2PublicTests" time="0.003"/>
    <testcase name="testMethodUsePotions4" classname="harrypotter.tests.M2PublicTests" time="0.005"/>
    <testcase name="testSecondTaskClassNotifiesListenerWhenTwoChampionsWin" classname="harrypotter.tests.M2PublicTests" time="0.003">
      <failure>java.lang.AssertionError: Upon completion of the second task, the SecondTask notifies the Tournament class
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at harrypotter.tests.M2PublicTests.testSecondTaskClassNotifiesListenerWhenTwoChampionsWin(M2PublicTests.java:5148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
    <testcase name="testTurnAfterBothChampionsDieByDragonFire" classname="harrypotter.tests.M2PublicTests" time="0.003">
      <failure>java.lang.AssertionError: The damage inflicted on the champion by the dragon fire is incorrect expected:&lt;100&gt; but was:&lt;150&gt;
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at harrypotter.tests.M2PublicTests.testTurnAfterBothChampionsDieByDragonFire(M2PublicTests.java:5594)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
    <testcase name="testOnHufflepuffTraitFirstTaskClass1" classname="harrypotter.tests.M2PublicTests" time="0.004"/>
    <testcase name="testOnHufflepuffTraitFirstTaskClass2" classname="harrypotter.tests.M2PublicTests" time="0.029"/>
    <testcase name="testMethodCastHealingSpell1" classname="harrypotter.tests.M2PublicTests" time="0.005"/>
    <testcase name="testCurrentChampIsSetCorrectly" classname="harrypotter.tests.M2PublicTests" time="0.006"/>
    <testcase name="testTaskClassImplementsWizardListener" classname="harrypotter.tests.M2PublicTests" time="0.005"/>
    <testcase name="testFirstTaskListenerIsSetCorrectly" classname="harrypotter.tests.M2PublicTests" time="0.033">
      <failure>java.lang.AssertionError: The instance variable listener of the FirstTask should be set correctly after the beginning of the Tournament. expected:&lt;harrypotter.model.tournament.Tournament@6c7d52d8&gt; but was:&lt;null&gt;
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at harrypotter.tests.M2PublicTests.testFirstTaskListenerIsSetCorrectly(M2PublicTests.java:1603)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
    <testcase name="testOnSlytherinTraitInFirstTaskClass3" classname="harrypotter.tests.M2PublicTests" time="0.003">
      <failure>java.lang.AssertionError: In FirstTask, onSlytherinTrait method should end the turn and update the champion's traitCooldown expected:&lt;5&gt; but was:&lt;0&gt;
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at harrypotter.tests.M2PublicTests.testOnSlytherinTraitInFirstTaskClass3(M2PublicTests.java:4745)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
    <testcase name="testMoveForwardToEggCellThirdTask" classname="harrypotter.tests.M2PublicTests" time="0.004">
      <failure>java.lang.AssertionError: When a champion moves forward from a cell, it should be converted to an EmptyCell  expected:&lt;class harrypotter.model.world.EmptyCell&gt; but was:&lt;class harrypotter.model.world.ChampionCell&gt;
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at harrypotter.tests.M2PublicTests.testMoveForwardToEggCellThirdTask(M2PublicTests.java:3120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
    <testcase name="testMethodsInTaskListenerInterface" classname="harrypotter.tests.M2PublicTests" time="0.002"/>
    <testcase name="testInstanceVariableMarkedCellsInFirstTaskClass" classname="harrypotter.tests.M2PublicTests" time="0.001"/>
    <testcase name="testCastDamagingSpellOnObstacleCell1" classname="harrypotter.tests.M2PublicTests" time="0.003">
      <failure>java.lang.AssertionError: In the thirdTask, when the current champion casts a damaging spell, the damage value of the spell should be deducted from the hp of the obstacles expected:&lt;700&gt; but was:&lt;1000&gt;
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at harrypotter.tests.M2PublicTests.testCastDamagingSpellOnObstacleCell1(M2PublicTests.java:242)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
    <testcase name="testTurnAfterCurrentChampionDieByMerPerson" classname="harrypotter.tests.M2PublicTests" time="0.002">
      <failure>java.lang.AssertionError: The damage inflicted to the current champion is incorrect expected:&lt;850&gt; but was:&lt;600&gt;
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at harrypotter.tests.M2PublicTests.testTurnAfterCurrentChampionDieByMerPerson(M2PublicTests.java:5686)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
    <testcase name="testOnSlytherinTraitInSecondTaskClass3" classname="harrypotter.tests.M2PublicTests" time="0.002">
      <failure>java.lang.AssertionError: In SecondTask, onSlytherinTrait method should end the turn and update the champion's traitCooldown expected:&lt;3&gt; but was:&lt;0&gt;
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at harrypotter.tests.M2PublicTests.testOnSlytherinTraitInSecondTaskClass3(M2PublicTests.java:4809)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
    <testcase name="testMethodFireIsCalledPerTurn1" classname="harrypotter.tests.M2PublicTests" time="0.031"/>
    <testcase name="testMarkCellsObstcles" classname="harrypotter.tests.M2PublicTests" time="0.046">
      <failure>java.lang.AssertionError: One or both of the marked cells is in an incorrect location
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at harrypotter.tests.M2PublicTests.testMarkCellsObstcles(M2PublicTests.java:2035)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
    <testcase name="testFireEffectOnOtherCellTypes" classname="harrypotter.tests.M2PublicTests" time="0.056"/>
    <testcase name="testOnRavenclawTraitInSecondTaskClass1" classname="harrypotter.tests.M2PublicTests" time="0.003">
      <failure>java.lang.AssertionError: In SecondTask, onRavenclawTrait should return the directions to the treasure cell correctly expected:&lt;2&gt; but was:&lt;1&gt;
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at harrypotter.tests.M2PublicTests.testOnRavenclawTraitInSecondTaskClass1(M2PublicTests.java:4377)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
    <testcase name="testOnRavenclawTraitInSecondTaskClass2" classname="harrypotter.tests.M2PublicTests" time="0.002"/>
    <testcase name="testCastRelocatingSpellOnObstacleCell" classname="harrypotter.tests.M2PublicTests" time="0.036">
      <failure>java.lang.AssertionError: In FirstTask, when a relocating spell is applied on an obstacle cell, the target cell should be an obstacle cell
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at harrypotter.tests.M2PublicTests.testCastRelocatingSpellOnObstacleCell(M2PublicTests.java:447)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
    <testcase name="testChampionsLocationIsSetCorrectly" classname="harrypotter.tests.M2PublicTests" time="0.002"/>
    <testcase name="testMethodUseSpell1" classname="harrypotter.tests.M2PublicTests" time="1.007">
      <error>org.junit.runners.model.TestTimedOutException: test timed out after 1000 milliseconds
	at harrypotter.model.tournament.Task.&lt;init&gt;(Task.java:59)
	at harrypotter.model.tournament.SecondTask.&lt;init&gt;(SecondTask.java:28)
	at harrypotter.tests.M2PublicTests$27.&lt;init&gt;(M2PublicTests.java:2810)
	at harrypotter.tests.M2PublicTests.testMethodUseSpell1(M2PublicTests.java:2810)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</error>
    </testcase>
    <testcase name="testMethodsInWizardListenerInterface" classname="harrypotter.tests.M2PublicTests" time="0.012"/>
    <testcase name="testDragonFireOnOtherChampionWhenChampionGoesToEggCell" classname="harrypotter.tests.M2PublicTests" time="0.077">
      <failure>java.lang.AssertionError: The damage inflicted on the other champion by the dragon fire is incorrect, dragon should fire even if the current champion reaches the egg cell  expected:&lt;150&gt; but was:&lt;0&gt;
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at harrypotter.tests.M2PublicTests.testDragonFireOnOtherChampionWhenChampionGoesToEggCell(M2PublicTests.java:942)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
    <testcase name="testWizardListenerVariableInWizardClass" classname="harrypotter.tests.M2PublicTests" time="0.008"/>
    <testcase name="testOnRavenclawTraitInFirstTaskClass2" classname="harrypotter.tests.M2PublicTests" time="0.047"/>
    <testcase name="testOnRavenclawTraitInFirstTaskClass3" classname="harrypotter.tests.M2PublicTests" time="0.014"/>
    <testcase name="testBeginTournamentIntializesFirstTaskCorrectly" classname="harrypotter.tests.M2PublicTests" time="0.035"/>
    <testcase name="testTraitCooldownIsDecrementedPerTurn" classname="harrypotter.tests.M2PublicTests" time="0.005">
      <failure>java.lang.AssertionError: In each turn, the trait cool down of the champions should be decremented by 1 expected:&lt;2&gt; but was:&lt;3&gt;
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at harrypotter.tests.M2PublicTests.testTraitCooldownIsDecrementedPerTurn(M2PublicTests.java:5530)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
    <testcase name="testTaskListenerVariableInTaskClass" classname="harrypotter.tests.M2PublicTests" time="0.033"/>
    <testcase name="testWizardListenerIsInterface" classname="harrypotter.tests.M2PublicTests" time="0.008"/>
    <testcase name="testOnSlytherinTraitInThirdTaskClass1" classname="harrypotter.tests.M2PublicTests" time="0.005">
      <failure>java.lang.AssertionError: In ThirdTask, onSlytherinTrait should allow the champion to move two cells in the map at a time
	at org.junit.Assert.fail(Assert.java:88)
	at harrypotter.tests.M2PublicTests.testOnSlytherinTraitInThirdTaskClass1(M2PublicTests.java:4863)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
    <testcase name="testDragonFireDamageCurrentChamp" classname="harrypotter.tests.M2PublicTests" time="0.005">
      <failure>java.lang.AssertionError: The damage inflicted on the champion by the dragon fire is incorrect expected:&lt;0&gt; but was:&lt;-50&gt;
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at harrypotter.tests.M2PublicTests.testDragonFireDamageCurrentChamp(M2PublicTests.java:840)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
    <testcase name="testConstructorFirstTaskInitialization" classname="harrypotter.tests.M2PublicTests" time="0.03">
      <failure>java.lang.AssertionError: raven'listener is incorrectly set
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at harrypotter.tests.M2PublicTests.testConstructorFirstTaskInitialization(M2PublicTests.java:689)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
    <testcase name="testMethodEncounterMerpersonIsCalledPerTurn2" classname="harrypotter.tests.M2PublicTests" time="0.008"/>
    <testcase name="testTaskListenerIsInterface" classname="harrypotter.tests.M2PublicTests" time="0.007"/>
    <testcase name="testOnGryffindorTraitSubClass" classname="harrypotter.tests.M2PublicTests" time="0.0"/>
    <testcase name="testThirdTaskClassNotifiesListenerWhenAChampionWins" classname="harrypotter.tests.M2PublicTests" time="0.005"/>
    <testcase name="testInstanceVariableMarkedCellsInFirstTaskClassGetter" classname="harrypotter.tests.M2PublicTests" time="0.0"/>
    <testcase name="testOnGryffindorTrait1" classname="harrypotter.tests.M2PublicTests" time="0.034"/>
    <testcase name="testOnGryffindorTrait2" classname="harrypotter.tests.M2PublicTests" time="0.0"/>
    <testcase name="testOnGryffindorTrait3" classname="harrypotter.tests.M2PublicTests" time="0.0"/>
    <testcase name="testGetTargetPoint" classname="harrypotter.tests.M2PublicTests" time="0.002"/>
    <testcase name="testMoveForwardToTreasureCell" classname="harrypotter.tests.M2PublicTests" time="0.001">
      <failure>java.lang.AssertionError: When a champion moves forward from a cell, it should be converted to an EmptyCell  expected:&lt;class harrypotter.model.world.EmptyCell&gt; but was:&lt;class harrypotter.model.world.ChampionCell&gt;
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at harrypotter.tests.M2PublicTests.testMoveForwardToTreasureCell(M2PublicTests.java:3202)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
    <testcase name="testCastRelocatingSpellCallsUseSpell" classname="harrypotter.tests.M2PublicTests" time="0.006"/>
    <testcase name="testInstanceVariableMarkedCellsInFirstTaskClassSetter" classname="harrypotter.tests.M2PublicTests" time="0.004"/>
    <testcase name="testEncounterMerPersonNotCurrentChampion" classname="harrypotter.tests.M2PublicTests" time="0.09"/>
    <testcase name="testCastDamagingSpellOnChampionCellThirdTaskHufflepuffWizard" classname="harrypotter.tests.M2PublicTests" time="0.046"/>
    <testcase name="testOnHuffelpuffTraitFirstTaskScenario" classname="harrypotter.tests.M2PublicTests" time="0.008"/>
    <testcase name="testTraitActivatedPerTurn" classname="harrypotter.tests.M2PublicTests" time="0.002">
      <failure>java.lang.AssertionError: In each turn, the trait can be activated for one turn per player
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at harrypotter.tests.M2PublicTests.testTraitActivatedPerTurn(M2PublicTests.java:5469)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
    <testcase name="testTurnAfterOtherChampionDieByDragonFire" classname="harrypotter.tests.M2PublicTests" time="0.0">
      <failure>java.lang.AssertionError: The damage inflicted on the champion by the dragon fire is incorrect expected:&lt;100&gt; but was:&lt;150&gt;
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at harrypotter.tests.M2PublicTests.testTurnAfterOtherChampionDieByDragonFire(M2PublicTests.java:5784)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
    <testcase name="testOnSlytherinTraitThirdTaskSetsDirectionVariableInSlythWizard" classname="harrypotter.tests.M2PublicTests" time="0.0"/>
    <testcase name="testCastRelocatingSpellCallsFinalizeAction" classname="harrypotter.tests.M2PublicTests" time="0.061"/>
    <testcase name="testOnRavenclawTraitInThirdTaskClass2" classname="harrypotter.tests.M2PublicTests" time="0.05"/>
    <testcase name="testOnRavenclawTraitInThirdTaskClass3" classname="harrypotter.tests.M2PublicTests" time="0.045"/>
    <testcase name="testThirdTaskClassHandlesNullListenerWhenAChampionWins" classname="harrypotter.tests.M2PublicTests" time="0.002"/>
    <testcase name="testMarkCellsCount" classname="harrypotter.tests.M2PublicTests" time="0.006"/>
    <testcase name="testMarkCellsRange" classname="harrypotter.tests.M2PublicTests" time="0.088">
      <failure>java.lang.AssertionError: The range of the chosen cells to be marked is incorrect
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at harrypotter.tests.M2PublicTests.testMarkCellsRange(M2PublicTests.java:2102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
    <testcase name="testMoveForwardToEggCell" classname="harrypotter.tests.M2PublicTests" time="0.059">
      <failure>java.lang.AssertionError: When a champion moves forward from a cell, it should be converted to an EmptyCell  expected:&lt;class harrypotter.model.world.EmptyCell&gt; but was:&lt;class harrypotter.model.world.ChampionCell&gt;
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at harrypotter.tests.M2PublicTests.testMoveForwardToEggCell(M2PublicTests.java:3044)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
    <testcase name="testHufflepuffWizardNotifiesListener" classname="harrypotter.tests.M2PublicTests" time="0.029"/>
    <testcase name="testMoveForwardToEmptyCell" classname="harrypotter.tests.M2PublicTests" time="0.046">
      <failure>java.lang.AssertionError: When a champion moves from a cell, it should be converted to an EmptyCell  expected:&lt;class harrypotter.model.world.EmptyCell&gt; but was:&lt;class harrypotter.model.world.ChampionCell&gt;
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at harrypotter.tests.M2PublicTests.testMoveForwardToEmptyCell(M2PublicTests.java:3161)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
    <testcase name="testCastDamagingSpellOnChampionCell1" classname="harrypotter.tests.M2PublicTests" time="0.05">
      <failure>java.lang.AssertionError: In FirstTask, when the current champion casts a damaging spell on a Champion cell, the hp of the champion in the cell should be affected expected:&lt;450&gt; but was:&lt;300&gt;
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at harrypotter.tests.M2PublicTests.testCastDamagingSpellOnChampionCell1(M2PublicTests.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
    <testcase name="testFirstTaskClassNotifiesListenerWhenAllChampionsDie" classname="harrypotter.tests.M2PublicTests" time="0.048">
      <failure>java.lang.AssertionError: Upon completion of the first task, the FirstTask notifies the Tournament class
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at harrypotter.tests.M2PublicTests.testFirstTaskClassNotifiesListenerWhenAllChampionsDie(M2PublicTests.java:1488)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
    <testcase name="testWizardListenerVariableGetter" classname="harrypotter.tests.M2PublicTests" time="0.002"/>
    <testcase name="testGryffindorWizardNotifiesListener" classname="harrypotter.tests.M2PublicTests" time="0.01"/>
    <testcase name="testSpellsCooldownIsDecrementedPerTurn" classname="harrypotter.tests.M2PublicTests" time="0.039"/>
    <testcase name="testMerPersonDamageOnChampionInTreassureCell" classname="harrypotter.tests.M2PublicTests" time="0.019"/>
    <testcase name="testOnSlytherinTraitSecondTaskSetsDirectionVariableInSlythWizard" classname="harrypotter.tests.M2PublicTests" time="0.019"/>
    <testcase name="testWizardListenerVariableSetter" classname="harrypotter.tests.M2PublicTests" time="0.005"/>
    <testcase name="testMoveForwardToCollectibeCell" classname="harrypotter.tests.M2PublicTests" time="0.017">
      <failure>java.lang.AssertionError: When a champion moves from a cell, it should be converted to an EmptyCell  expected:&lt;class harrypotter.model.world.EmptyCell&gt; but was:&lt;class harrypotter.model.world.ChampionCell&gt;
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at harrypotter.tests.M2PublicTests.testMoveForwardToCollectibeCell(M2PublicTests.java:3001)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
    <testcase name="testFirstTaskClassHandlesNullListenerWhenFourChampionsWin" classname="harrypotter.tests.M2PublicTests" time="0.003"/>
    <testcase name="testEncounterTwoMerPeople" classname="harrypotter.tests.M2PublicTests" time="0.086"/>
    <testcase name="testOnHufflepuffTraitSecondTaskClass1" classname="harrypotter.tests.M2PublicTests" time="0.04"/>
    <testcase name="testTournamentClassImplementsTaskListener" classname="harrypotter.tests.M2PublicTests" time="0.009"/>
    <testcase name="testMethodHealingSpellCallsFinalizeAction" classname="harrypotter.tests.M2PublicTests" time="0.081"/>
    <testcase name="testTaskListenerVariableGetter" classname="harrypotter.tests.M2PublicTests" time="0.019"/>
    <testcase name="testEncounterMerPeopleNotInRangeClose" classname="harrypotter.tests.M2PublicTests" time="0.031"/>
    <testcase name="testFirstTaskClassNotifiesListenerWhenFourChampionsWin" classname="harrypotter.tests.M2PublicTests" time="0.012">
      <failure>java.lang.AssertionError: Upon completion of the first task, the FirstTask notifies the Tournament class
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at harrypotter.tests.M2PublicTests.testFirstTaskClassNotifiesListenerWhenFourChampionsWin(M2PublicTests.java:1568)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
  </testsuite>
</testrun>
