<?xml version="1.0" encoding="UTF-8"?><testrun name="Rerun Rerun M3PublicTests (Failed Tests first)" project="harrypotter" tests="83" started="83" failures="8" errors="25" ignored="0">
  <testsuite name="harrypotter.tests.M3PublicTests" time="0.125">
    <testcase name="testSlytherinMovesToWallCellOnTraitActivated" classname="harrypotter.tests.M3PublicTests" time="0.002">
      <error>java.lang.Error: Unresolved compilation problem: 
	Unreachable catch block for InvalidTargetCellException. This exception is never thrown from the try statement body
&#13;
	at harrypotter.tests.M3PublicTests.onSlythMovesToInvalidCellsHelper(M3PublicTests.java:4874)&#13;
	at harrypotter.tests.M3PublicTests.testSlytherinMovesToWallCellOnTraitActivated(M3PublicTests.java:3980)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:483)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testRelocatingObstacleToCupThirdTask" classname="harrypotter.tests.M3PublicTests" time="0.003">
      <error>java.lang.Error: Unresolved compilation problem: 
	Unreachable code
&#13;
	at harrypotter.model.tournament.Task.castRelocatingSpell(Task.java:328)&#13;
	at harrypotter.tests.M3PublicTests.relocateToInvalidDestination(M3PublicTests.java:4989)&#13;
	at harrypotter.tests.M3PublicTests.testRelocatingObstacleToCupThirdTask(M3PublicTests.java:3565)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:483)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testUseOnSlytherinWhileInCoolDownThirdTask" classname="harrypotter.tests.M3PublicTests" time="0.002">
      <failure>java.lang.AssertionError: If a champion tries to use his/her trait while he/she is still in coolDown, an exception of type InCooldownException should be thrown with the correct "remainingTurns"  expected:&lt;9&gt; but was:&lt;0&gt;&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at org.junit.Assert.failNotEquals(Assert.java:743)&#13;
	at org.junit.Assert.assertEquals(Assert.java:118)&#13;
	at org.junit.Assert.assertEquals(Assert.java:555)&#13;
	at harrypotter.tests.M3PublicTests.testUseOnSlytherinWhileInCoolDownThirdTask(M3PublicTests.java:4359)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:483)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testRelocatingPotionSecondTask" classname="harrypotter.tests.M3PublicTests" time="0.001">
      <error>java.lang.Error: Unresolved compilation problem: 
	Unreachable code
&#13;
	at harrypotter.model.tournament.Task.castRelocatingSpell(Task.java:328)&#13;
	at harrypotter.tests.M3PublicTests.relocateInvalidTarget(M3PublicTests.java:4928)&#13;
	at harrypotter.tests.M3PublicTests.testRelocatingPotionSecondTask(M3PublicTests.java:3731)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:483)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testInCooldownExceptionExtendsException" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testRelocatingChampionToWallThirdTask" classname="harrypotter.tests.M3PublicTests" time="0.001">
      <error>java.lang.Error: Unresolved compilation problem: 
	Unreachable code
&#13;
	at harrypotter.model.tournament.Task.castRelocatingSpell(Task.java:328)&#13;
	at harrypotter.tests.M3PublicTests.relocateToInvalidDestination(M3PublicTests.java:4989)&#13;
	at harrypotter.tests.M3PublicTests.testRelocatingChampionToWallThirdTask(M3PublicTests.java:2861)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:483)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testNotEnoughIPExceptionReqIPGetter" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testCastingDamagingSpellWithNotEnoughIPInFirstTask" classname="harrypotter.tests.M3PublicTests" time="0.002">
      <failure>java.lang.AssertionError: In FirstTask, when the current champion casts a damaging spell on a Champion cell while not having enough IP, NotEnoughIPException should be thrown with the correct "remainingIP"  expected:&lt;100&gt; but was:&lt;50&gt;&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at org.junit.Assert.failNotEquals(Assert.java:743)&#13;
	at org.junit.Assert.assertEquals(Assert.java:118)&#13;
	at org.junit.Assert.assertEquals(Assert.java:555)&#13;
	at harrypotter.tests.M3PublicTests.testCastingDamagingSpellWithNotEnoughIPInFirstTask(M3PublicTests.java:423)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:483)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testMoveOutOfBordersFromCornerSecondTask" classname="harrypotter.tests.M3PublicTests" time="0.005">
      <error>harrypotter.exceptions.InvalidTargetCellException: You are Trying to Move to an Invalid Target Cell&#13;
	at harrypotter.model.tournament.SecondTask.moveRight(SecondTask.java:352)&#13;
	at harrypotter.tests.M3PublicTests.testMoveOutOfBordersFromCornerSecondTask(M3PublicTests.java:1884)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:483)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testRelocatingObstacleOutOfRangeSecondTask" classname="harrypotter.tests.M3PublicTests" time="0.001">
      <error>java.lang.Error: Unresolved compilation problem: 
	Unreachable code
&#13;
	at harrypotter.model.tournament.Task.castRelocatingSpell(Task.java:328)&#13;
	at harrypotter.tests.M3PublicTests.testRelocatingObstacleOutOfRangeSecondTask(M3PublicTests.java:3130)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:483)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testSlytherinMovesToTreasureCellOnTraitActivated" classname="harrypotter.tests.M3PublicTests" time="0.001">
      <error>java.lang.Error: Unresolved compilation problem: 
	Unreachable catch block for InvalidTargetCellException. This exception is never thrown from the try statement body
&#13;
	at harrypotter.tests.M3PublicTests.onSlythMovesToInvalidCellsHelper(M3PublicTests.java:4874)&#13;
	at harrypotter.tests.M3PublicTests.testSlytherinMovesToTreasureCellOnTraitActivated(M3PublicTests.java:3935)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:483)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testInCooldownExceptionConstructorExists" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testInvalidActionExceptionAbstract" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testDamagingCupCellThirdTask" classname="harrypotter.tests.M3PublicTests" time="0.021"/>
    <testcase name="testNotEnoughIPExceptionReqIPSetter" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testOutOfBordersExceptionConstructorExists2" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testRelocatingChampionToCollectibleSecondTask" classname="harrypotter.tests.M3PublicTests" time="0.001">
      <error>java.lang.Error: Unresolved compilation problem: 
	Unreachable code
&#13;
	at harrypotter.model.tournament.Task.castRelocatingSpell(Task.java:328)&#13;
	at harrypotter.tests.M3PublicTests.relocateToInvalidDestination(M3PublicTests.java:4989)&#13;
	at harrypotter.tests.M3PublicTests.testRelocatingChampionToCollectibleSecondTask(M3PublicTests.java:2699)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:483)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testSlytherinMovesToCellOutOfBordersOnTraitActivatedSecondTask" classname="harrypotter.tests.M3PublicTests" time="0.001">
      <error>java.lang.Error: Unresolved compilation problems: 
	Unreachable catch block for OutOfBordersException. This exception is never thrown from the try statement body
	Unreachable catch block for OutOfBordersException. This exception is never thrown from the try statement body
	Unreachable catch block for OutOfBordersException. This exception is never thrown from the try statement body
	Unreachable catch block for OutOfBordersException. This exception is never thrown from the try statement body
&#13;
	at harrypotter.tests.M3PublicTests.SlytherinMovesToCellOutOfBordersOnTraitActivatedHelper(M3PublicTests.java:5139)&#13;
	at harrypotter.tests.M3PublicTests.testSlytherinMovesToCellOutOfBordersOnTraitActivatedSecondTask(M3PublicTests.java:3864)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:483)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testRelocatingObstacleToChampionSecondTask" classname="harrypotter.tests.M3PublicTests" time="0.001">
      <error>java.lang.Error: Unresolved compilation problem: 
	Unreachable code
&#13;
	at harrypotter.model.tournament.Task.castRelocatingSpell(Task.java:328)&#13;
	at harrypotter.tests.M3PublicTests.relocateToInvalidDestination(M3PublicTests.java:4989)&#13;
	at harrypotter.tests.M3PublicTests.testRelocatingObstacleToChampionSecondTask(M3PublicTests.java:3404)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:483)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testRelocatingChampionToObstacleFirstTask" classname="harrypotter.tests.M3PublicTests" time="0.001">
      <error>java.lang.Error: Unresolved compilation problem: 
	Unreachable code
&#13;
	at harrypotter.model.tournament.Task.castRelocatingSpell(Task.java:328)&#13;
	at harrypotter.tests.M3PublicTests.relocateToInvalidDestination(M3PublicTests.java:4989)&#13;
	at harrypotter.tests.M3PublicTests.testRelocatingChampionToObstacleFirstTask(M3PublicTests.java:2781)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:483)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testConstructorInitializationInCooldownException" classname="harrypotter.tests.M3PublicTests" time="0.001">
      <failure>java.lang.AssertionError: In InCooldownException class, the variable remainingTurns is not set correctly in the constructor expected:&lt;9&gt; but was:&lt;0&gt;&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at org.junit.Assert.failNotEquals(Assert.java:743)&#13;
	at org.junit.Assert.assertEquals(Assert.java:118)&#13;
	at harrypotter.tests.M3PublicTests.testConstructorInitializationInCooldownException(M3PublicTests.java:847)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:483)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testUseOnHufflepuffWhileInCoolDownThirdTask" classname="harrypotter.tests.M3PublicTests" time="0.001">
      <failure>java.lang.AssertionError: In ThirdTask, The Hufflepuff trait should be always activated and should never throw an InCooldownException. harrypotter.exceptions.InCooldownException: Cannot make a move Yet. remaining Turns: -1&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at harrypotter.tests.M3PublicTests.testUseOnHufflepuffWhileInCoolDownThirdTask(M3PublicTests.java:4213)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:483)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testRelocatingObstacleToObstacleFirstTask" classname="harrypotter.tests.M3PublicTests" time="0.001">
      <error>java.lang.Error: Unresolved compilation problem: 
	Unreachable code
&#13;
	at harrypotter.model.tournament.Task.castRelocatingSpell(Task.java:328)&#13;
	at harrypotter.tests.M3PublicTests.relocateToInvalidDestination(M3PublicTests.java:4989)&#13;
	at harrypotter.tests.M3PublicTests.testRelocatingObstacleToObstacleFirstTask(M3PublicTests.java:3646)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:483)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testInvalidActionExceptionExtendsException" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testCastingRelocatingSpellWithNotEnoughIPInFirstTask" classname="harrypotter.tests.M3PublicTests" time="0.001">
      <error>java.lang.Error: Unresolved compilation problem: 
	Unreachable code
&#13;
	at harrypotter.model.tournament.Task.castRelocatingSpell(Task.java:328)&#13;
	at harrypotter.tests.M3PublicTests.testCastingRelocatingSpellWithNotEnoughIPInFirstTask(M3PublicTests.java:681)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:483)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testOutOfRangeExceptionExtendsException" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testMoveRightToObstacleCell" classname="harrypotter.tests.M3PublicTests" time="0.002"/>
    <testcase name="testMoveLeftToObstacleCell" classname="harrypotter.tests.M3PublicTests" time="0.002"/>
    <testcase name="testRelocatingTreasureCellSecondTask" classname="harrypotter.tests.M3PublicTests" time="0.001">
      <error>java.lang.Error: Unresolved compilation problem: 
	Unreachable code
&#13;
	at harrypotter.model.tournament.Task.castRelocatingSpell(Task.java:328)&#13;
	at harrypotter.tests.M3PublicTests.relocateInvalidTarget(M3PublicTests.java:4928)&#13;
	at harrypotter.tests.M3PublicTests.testRelocatingTreasureCellSecondTask(M3PublicTests.java:3815)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:483)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testCastDamagingSpellWhileCoolingDownThirdTask" classname="harrypotter.tests.M3PublicTests" time="0.001">
      <failure>java.lang.AssertionError: If a champion tries to use a spell while it is still in coolDown, an exception of type InCooldownException should be thrown with the correct "remainingTurns"  expected:&lt;4&gt; but was:&lt;0&gt;&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at org.junit.Assert.failNotEquals(Assert.java:743)&#13;
	at org.junit.Assert.assertEquals(Assert.java:118)&#13;
	at org.junit.Assert.assertEquals(Assert.java:555)&#13;
	at harrypotter.tests.M3PublicTests.testCastDamagingSpellWhileCoolingDownThirdTask(M3PublicTests.java:126)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:483)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testConstructorInitializationInvalidTargetCellException" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testInvalidTargetCellExceptionConstructorExists2" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testOutOfBordersExceptionConstructorExists" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testUseOnHufflepuffWhileInCoolDownFirstTask" classname="harrypotter.tests.M3PublicTests" time="0.001">
      <failure>java.lang.AssertionError: If a champion tries to use his/her trait while he/she is still in coolDown, an exception of type InCooldownException should be thrown with the correct "remainingTurns"  expected:&lt;2&gt; but was:&lt;0&gt;&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at org.junit.Assert.failNotEquals(Assert.java:743)&#13;
	at org.junit.Assert.assertEquals(Assert.java:118)&#13;
	at org.junit.Assert.assertEquals(Assert.java:555)&#13;
	at harrypotter.tests.M3PublicTests.testUseOnHufflepuffWhileInCoolDownFirstTask(M3PublicTests.java:4142)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:483)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testOutOfBordersExceptionExtendsException" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testMoveBackwardToIncorrectTreasureCell" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testMoveLeftToWallCell" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testNotEnoughIPExceptionExtendsException" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testConstructorInitializationNotEnoughIPException" classname="harrypotter.tests.M3PublicTests" time="0.002"/>
    <testcase name="testNotEnoughResourcesExceptionExtendsException" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testInvalidActionExceptionConstructorExists" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testRelocatingEmptyCellThirdTask" classname="harrypotter.tests.M3PublicTests" time="0.0">
      <error>java.lang.Error: Unresolved compilation problem: 
	Unreachable code
&#13;
	at harrypotter.model.tournament.Task.castRelocatingSpell(Task.java:328)&#13;
	at harrypotter.tests.M3PublicTests.relocateInvalidTarget(M3PublicTests.java:4928)&#13;
	at harrypotter.tests.M3PublicTests.testRelocatingEmptyCellThirdTask(M3PublicTests.java:2946)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:483)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testNotEnoughIPExceptionConstructorExists" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testOutOfRangeExceptionConstructorExists" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testUseOnGryffindorTraitWhileInCoolDownSecondTask" classname="harrypotter.tests.M3PublicTests" time="0.001">
      <error>harrypotter.exceptions.InvalidTargetCellException: You are Trying to Move to an Invalid Target Cell&#13;
	at harrypotter.model.tournament.SecondTask.moveBackward(SecondTask.java:263)&#13;
	at harrypotter.tests.M3PublicTests.testUseOnGryffindorTraitWhileInCoolDownSecondTask(M3PublicTests.java:4044)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:483)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)&#13;
&#13;
</error>
    </testcase>
    <testcase name="tesInvalidTargetCellExceptionExtendsException" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testRelocatingChampionOutOfRangeFirstTask" classname="harrypotter.tests.M3PublicTests" time="0.001">
      <error>java.lang.Error: Unresolved compilation problem: 
	Unreachable code
&#13;
	at harrypotter.model.tournament.Task.castRelocatingSpell(Task.java:328)&#13;
	at harrypotter.tests.M3PublicTests.testRelocatingChampionOutOfRangeFirstTask(M3PublicTests.java:2428)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:483)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testCastRelocationSpellWhileCoolingDownFirstTask" classname="harrypotter.tests.M3PublicTests" time="0.0">
      <error>java.lang.Error: Unresolved compilation problem: 
	Unreachable code
&#13;
	at harrypotter.model.tournament.Task.castRelocatingSpell(Task.java:328)&#13;
	at harrypotter.tests.M3PublicTests.testCastRelocationSpellWhileCoolingDownFirstTask(M3PublicTests.java:790)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:483)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testCastRelocatingSpellOnTargetOutOfBordersThirdTask" classname="harrypotter.tests.M3PublicTests" time="0.001">
      <error>java.lang.Error: Unresolved compilation problems: 
	Unreachable catch block for OutOfBordersException. This exception is never thrown from the try statement body
	Unreachable catch block for OutOfBordersException. This exception is never thrown from the try statement body
	Unreachable catch block for OutOfBordersException. This exception is never thrown from the try statement body
	Unreachable catch block for OutOfBordersException. This exception is never thrown from the try statement body
&#13;
	at harrypotter.tests.M3PublicTests.castRelocatingSpellOnTargetOutOfBordersHelper(M3PublicTests.java:4560)&#13;
	at harrypotter.tests.M3PublicTests.testCastRelocatingSpellOnTargetOutOfBordersThirdTask(M3PublicTests.java:729)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:483)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testCastingHealingSpellWithEnoughIP" classname="harrypotter.tests.M3PublicTests" time="0.002"/>
    <testcase name="testInvalidTargetCellExceptionConstructorExists" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testNotEnoughResourcesExceptionConstructorExists" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testNotEnoughIPExceptionInstanceVariables1" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testNotEnoughIPExceptionInstanceVariables2" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testRelocatingObstacleToCollectibleThirdTask" classname="harrypotter.tests.M3PublicTests" time="0.0">
      <error>java.lang.Error: Unresolved compilation problem: 
	Unreachable code
&#13;
	at harrypotter.model.tournament.Task.castRelocatingSpell(Task.java:328)&#13;
	at harrypotter.tests.M3PublicTests.relocateToInvalidDestination(M3PublicTests.java:4989)&#13;
	at harrypotter.tests.M3PublicTests.testRelocatingObstacleToCollectibleThirdTask(M3PublicTests.java:3485)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:483)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testInvalidActionExceptionConstructorExists2" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testDamagingPotionFirstTask" classname="harrypotter.tests.M3PublicTests" time="0.009"/>
    <testcase name="testCastHealingSpellWhileCoolingDownSecondTask" classname="harrypotter.tests.M3PublicTests" time="0.001">
      <error>harrypotter.exceptions.InvalidTargetCellException: You are Trying to Move to an Invalid Target Cell&#13;
	at harrypotter.model.tournament.SecondTask.moveRight(SecondTask.java:352)&#13;
	at harrypotter.tests.M3PublicTests.testCastHealingSpellWhileCoolingDownSecondTask(M3PublicTests.java:195)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:483)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testMoveBackwardToWallCell" classname="harrypotter.tests.M3PublicTests" time="0.002"/>
    <testcase name="testMoveBackwardToChampionCell" classname="harrypotter.tests.M3PublicTests" time="0.002"/>
    <testcase name="testNotEnoughResourcesExceptionConstructorExists2" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testMoveForwardToChampionCell" classname="harrypotter.tests.M3PublicTests" time="0.002"/>
    <testcase name="testUseOnRavenclawWhileInCoolDownThirdTask" classname="harrypotter.tests.M3PublicTests" time="0.001">
      <failure>java.lang.AssertionError: If a champion tries to use his/her trait while he/she is still in coolDown, an exception of type InCooldownException should be thrown with the correct "remainingTurns"  expected:&lt;6&gt; but was:&lt;0&gt;&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at org.junit.Assert.failNotEquals(Assert.java:743)&#13;
	at org.junit.Assert.assertEquals(Assert.java:118)&#13;
	at org.junit.Assert.assertEquals(Assert.java:555)&#13;
	at harrypotter.tests.M3PublicTests.testUseOnRavenclawWhileInCoolDownThirdTask(M3PublicTests.java:4284)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:483)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testNotEnoughIPExceptionRemIPGetter" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testInCooldownExceptionRemTurnsGetter" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testInCooldownExceptionInstanceVariables1" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testOutOfRangeExceptionAllowedRangeGetter" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testNotEnoughIPExceptionRemIPSetter" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testConstructorInitializationOutOfRangeException" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testRelocatingChampionOutOfBordersThirdTask" classname="harrypotter.tests.M3PublicTests" time="0.0">
      <error>java.lang.Error: Unresolved compilation problem: 
	Unreachable catch block for OutOfBordersException. This exception is never thrown from the try statement body
&#13;
	at harrypotter.tests.M3PublicTests.testRelocatingChampionOutOfBordersThirdTask(M3PublicTests.java:2365)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:483)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testCastingHealingSpellWithNotEnoughIPInThirdTask" classname="harrypotter.tests.M3PublicTests" time="0.002">
      <failure>java.lang.AssertionError: In ThirdTask, when the current champion casts a Healing spell while not having enough IP, NotEnoughIPException should be thrown with the correct "remainingIP"  expected:&lt;1&gt; but was:&lt;299&gt;&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at org.junit.Assert.failNotEquals(Assert.java:743)&#13;
	at org.junit.Assert.assertEquals(Assert.java:118)&#13;
	at org.junit.Assert.assertEquals(Assert.java:555)&#13;
	at harrypotter.tests.M3PublicTests.testCastingHealingSpellWithNotEnoughIPInThirdTask(M3PublicTests.java:634)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:483)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testInCooldownExceptionRemTurnsSetter" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testOutOfRangeExceptionAllowedRangeSetter" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testDamagingWallThirdTask" classname="harrypotter.tests.M3PublicTests" time="0.013"/>
    <testcase name="testNotEnoughResourcesExceptionAbstract" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testOutOfRangeExceptionInstanceVariables1" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testMoveOutOfBordersFromEdgeFirstTask" classname="harrypotter.tests.M3PublicTests" time="0.002"/>
    <testcase name="testConstructorInitializationOutOfBordersException" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testRelocatingObstacleOutOfBordersThirdTask" classname="harrypotter.tests.M3PublicTests" time="0.001">
      <error>java.lang.Error: Unresolved compilation problem: 
	Unreachable catch block for OutOfBordersException. This exception is never thrown from the try statement body
&#13;
	at harrypotter.tests.M3PublicTests.testRelocatingObstacleOutOfBordersThirdTask(M3PublicTests.java:3065)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:483)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testMoveForwardToIncorrectTreasureCell" classname="harrypotter.tests.M3PublicTests" time="0.0"/>
    <testcase name="testCastDamagingSpellOutOfBordersFirstTask" classname="harrypotter.tests.M3PublicTests" time="0.001">
      <error>java.lang.Error: Unresolved compilation problems: 
	Unreachable catch block for OutOfBordersException. This exception is never thrown from the try statement body
	Unreachable catch block for OutOfBordersException. This exception is never thrown from the try statement body
	Unreachable catch block for OutOfBordersException. This exception is never thrown from the try statement body
	Unreachable catch block for OutOfBordersException. This exception is never thrown from the try statement body
&#13;
	at harrypotter.tests.M3PublicTests.castDamagingSpellOutOfBordersHelper(M3PublicTests.java:4403)&#13;
	at harrypotter.tests.M3PublicTests.testCastDamagingSpellOutOfBordersFirstTask(M3PublicTests.java:42)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:483)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testCastingDamagingSpellWithEnoughIP" classname="harrypotter.tests.M3PublicTests" time="0.001"/>
    <testcase name="testSlytherinMovesToCupCellOnTraitActivated" classname="harrypotter.tests.M3PublicTests" time="0.001">
      <error>java.lang.Error: Unresolved compilation problem: 
	Unreachable catch block for InvalidTargetCellException. This exception is never thrown from the try statement body
&#13;
	at harrypotter.tests.M3PublicTests.onSlythMovesToInvalidCellsHelper(M3PublicTests.java:4874)&#13;
	at harrypotter.tests.M3PublicTests.testSlytherinMovesToCupCellOnTraitActivated(M3PublicTests.java:3893)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:483)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)&#13;
&#13;
</error>
    </testcase>
  </testsuite>
</testrun>
